"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-12

Squashed baseline (Aug 2026) - replaces the original migrations 0001-0021,
which are gone from the tree but live on in git history before this commit.
Squashed while the app had no production deployment, so no database ever has
to walk the old chain.

The table DDL is autogenerated from the models. Everything below that is
hand-carried, because the models cannot express it:

- the ``btree_gist`` extension and the exclusion constraints that need it
  (instructor/learner double-booking guards),
- ``shevaani_buffered_range`` - the prep/wind-down buffer around 1:1s,
- ``shevaani_sync_engagement`` and its triggers, which mirror sessions and
  one-on-ones into ``instructor_engagements`` so one exclusion constraint
  can see both calendars.

Seed data lives in 0002, not here.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Enum types are created explicitly before the tables. Inline sa.Enum would
# emit CREATE TYPE per table, and session_status / payment_provider are each
# shared by several tables - the second CREATE TYPE in the same transaction
# is an error.
user_role = postgresql.ENUM('learner', 'instructor', 'superuser', name='user_role', create_type=False)
payment_provider = postgresql.ENUM('stripe', 'razorpay', name='payment_provider', create_type=False)
block_reason = postgresql.ENUM('busy', 'holiday', 'sick', 'other', name='block_reason', create_type=False)
session_status = postgresql.ENUM('draft', 'published', 'cancelled', 'completed', name='session_status', create_type=False)
booking_status = postgresql.ENUM('pending', 'confirmed', 'waitlisted', 'cancelled', 'attended', 'no_show', name='booking_status', create_type=False)
meeting_status = postgresql.ENUM('pending', 'ready', 'failed', name='meeting_status', create_type=False)
payment_status = postgresql.ENUM('created', 'paid', 'failed', 'refunded', name='payment_status', create_type=False)
transcript_status = postgresql.ENUM('received', 'needs_review', 'resolved', 'failed', name='transcript_status', create_type=False)
credit_reason = postgresql.ENUM('purchase', 'booking_spend', 'booking_refund', 'session_cancelled', 'admin_grant', 'admin_revoke', 'signup_bonus', 'referral_bonus', name='credit_reason', create_type=False)
feedback_status = postgresql.ENUM('draft', 'published', name='feedback_status', create_type=False)

_ENUMS = [
    user_role, payment_provider, block_reason, session_status, booking_status,
    meeting_status, payment_status, transcript_status, credit_reason, feedback_status,
]


def upgrade() -> None:
    bind = op.get_bind()

    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # The buffer around a 1:1 - IMMUTABLE so it can serve in an exclusion
    # constraint (ex_one_on_one_buffer, added below).
    op.execute(
        """
        CREATE FUNCTION shevaani_buffered_range(
            ts_start timestamptz, ts_end timestamptz, buffer_minutes integer
        ) RETURNS tstzrange
        LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
        AS $$
            SELECT tstzrange(
                ts_start - make_interval(mins => buffer_minutes),
                ts_end   + make_interval(mins => buffer_minutes),
                '[)'
            )
        $$
        """
    )

    for enum in _ENUMS:
        enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packs',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('usd_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits > 0', name=op.f('ck_credit_packs_credits_positive')),
    sa.CheckConstraint('usd_cents > 0', name=op.f('ck_credit_packs_usd_cents_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_packs')),
    sa.UniqueConstraint('slug', name='uq_credit_packs_slug')
    )
    op.create_table('impromptu_topics',
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('track', sa.String(length=60), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impromptu_topics')),
    sa.UniqueConstraint('text', name='uq_impromptu_topics_text')
    )
    op.create_index(op.f('ix_impromptu_topics_category'), 'impromptu_topics', ['category'], unique=False)
    op.create_index(op.f('ix_impromptu_topics_track'), 'impromptu_topics', ['track'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_on_one_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_site_settings_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', user_role, nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('billing_country', sa.String(length=2), nullable=True),
    sa.Column('preferred_provider', payment_provider, nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sa.String(length=12), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('referral_code', name=op.f('uq_users_referral_code'))
    )
    op.create_table('webhook_events',
    sa.Column('provider', payment_provider, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_events_provider_event')
    )
    op.create_table('contact_messages',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handled_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contact_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_messages'))
    )
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verification_tokens_token_hash'))
    )
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('google_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_email', sa.String(length=320), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_google_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_google_credentials'))
    )
    op.create_table('instructor_blocks',
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', block_reason, nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_instructor_blocks_ends_after_starts')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_instructor_blocks_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name=op.f('fk_instructor_blocks_instructor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instructor_blocks'))
    )
    op.create_index(op.f('ix_instructor_blocks_instructor_id'), 'instructor_blocks', ['instructor_id'], unique=False)
    op.create_table('instructor_engagements',
    # The DB default matters: shevaani_sync_engagement inserts without an id.
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_instructor_engagements_ends_after_starts')),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name=op.f('fk_instructor_engagements_instructor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instructor_engagements')),
    sa.UniqueConstraint('source', 'source_id', name='uq_instructor_engagements_source')
    )
    op.create_table('meet_aliases',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meet_aliases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meet_aliases')),
    sa.UniqueConstraint('user_id', 'display_name', name='uq_meet_alias_user_name')
    )
    op.create_table('one_on_one_sessions',
    sa.Column('status', session_status, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_credits', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'draft'", name=op.f('ck_one_on_one_sessions_never_draft')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_one_on_one_sessions_ends_after_starts')),
    sa.CheckConstraint('price_credits >= 0', name=op.f('ck_one_on_one_sessions_price_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_one_on_one_sessions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name=op.f('fk_one_on_one_sessions_instructor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_one_on_one_sessions'))
    )
    op.create_index(op.f('ix_one_on_one_sessions_instructor_id'), 'one_on_one_sessions', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_one_on_one_sessions_starts_at'), 'one_on_one_sessions', ['starts_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_ip', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=True),
    sa.Column('provider', payment_provider, nullable=False),
    sa.Column('provider_order_id', sa.String(length=255), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', payment_status, nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['pack_id'], ['credit_packs.id'], name=op.f('fk_payments_pack_id_credit_packs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider', 'provider_order_id', name='uq_payments_provider_order')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('code_used', sa.String(length=32), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_credits', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('referrer_id <> referred_user_id', name=op.f('ck_referrals_not_self')),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name=op.f('fk_referrals_referred_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_referrals_referrer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('referred_user_id', name='uq_referrals_referred_user_id')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('sessions',
    sa.Column('status', session_status, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prep_material_url', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_seats', sa.Integer(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('price_credits', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_sessions_ends_after_starts')),
    sa.CheckConstraint('max_seats >= min_seats', name=op.f('ck_sessions_max_seats_gte_min')),
    sa.CheckConstraint('min_seats >= 1', name=op.f('ck_sessions_min_seats_positive')),
    sa.CheckConstraint('price_credits >= 0', name=op.f('ck_sessions_price_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_sessions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name=op.f('fk_sessions_instructor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_instructor_id'), 'sessions', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_sessions_slug'), 'sessions', ['slug'], unique=True)
    op.create_index(op.f('ix_sessions_starts_at'), 'sessions', ['starts_at'], unique=False)
    op.create_table('bookings',
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('one_on_one_id', sa.UUID(), nullable=True),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('status', booking_status, nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credits_spent', sa.Integer(), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('first_joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendance_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits_spent >= 0', name=op.f('ck_bookings_credits_non_negative')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_bookings_ends_after_starts')),
    sa.CheckConstraint('num_nonnulls(session_id, one_on_one_id) = 1', name=op.f('ck_bookings_exactly_one_parent')),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], name=op.f('fk_bookings_learner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['one_on_one_id'], ['one_on_one_sessions.id'], name=op.f('fk_bookings_one_on_one_id_one_on_one_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_bookings_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_learner_id'), 'bookings', ['learner_id'], unique=False)
    op.create_index(op.f('ix_bookings_one_on_one_id'), 'bookings', ['one_on_one_id'], unique=False)
    op.create_index(op.f('ix_bookings_session_id'), 'bookings', ['session_id'], unique=False)
    op.create_table('session_meetings',
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('one_on_one_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', meeting_status, nullable=False),
    sa.Column('calendar_event_id', sa.String(length=1024), nullable=True),
    sa.Column('host_google_email', sa.String(length=320), nullable=True),
    sa.Column('join_url', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('notetaker_dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(session_id, one_on_one_id) = 1', name=op.f('ck_session_meetings_exactly_one_parent')),
    sa.ForeignKeyConstraint(['one_on_one_id'], ['one_on_one_sessions.id'], name=op.f('fk_session_meetings_one_on_one_id_one_on_one_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_meetings_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_meetings'))
    )
    op.create_index('uq_session_meetings_one_on_one', 'session_meetings', ['one_on_one_id'], unique=True)
    op.create_index('uq_session_meetings_session', 'session_meetings', ['session_id'], unique=True)
    op.create_table('session_reminders',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('hours_before', sa.SmallInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_reminders_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_reminders')),
    sa.UniqueConstraint('session_id', 'hours_before', name='uq_session_reminders_session_hours')
    )
    op.create_index(op.f('ix_session_reminders_session_id'), 'session_reminders', ['session_id'], unique=False)
    op.create_table('session_transcripts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('provider_transcript_id', sa.String(length=128), nullable=False),
    sa.Column('status', transcript_status, nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('sentences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_transcripts_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_transcripts')),
    sa.UniqueConstraint('provider_transcript_id', name=op.f('uq_session_transcripts_provider_transcript_id')),
    sa.UniqueConstraint('session_id', name=op.f('uq_session_transcripts_session_id'))
    )
    op.create_table('credit_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', credit_reason, nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('delta <> 0', name=op.f('ck_credit_ledger_delta_non_zero')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_credit_ledger_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_credit_ledger_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_ledger_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger'))
    )
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('join_access_logs',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('one_on_one_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('num_nonnulls(session_id, one_on_one_id) = 1', name=op.f('ck_join_access_logs_exactly_one_parent')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_join_access_logs_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['one_on_one_id'], ['one_on_one_sessions.id'], name=op.f('fk_join_access_logs_one_on_one_id_one_on_one_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_join_access_logs_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_join_access_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join_access_logs'))
    )
    op.create_index(op.f('ix_join_access_logs_booking_id'), 'join_access_logs', ['booking_id'], unique=False)
    op.create_table('session_feedback',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('status', feedback_status, nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_md', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'published') OR (published_at IS NOT NULL)", name=op.f('ck_session_feedback_published_has_timestamp')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_session_feedback_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['session_transcripts.id'], name=op.f('fk_session_feedback_transcript_id_session_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_feedback')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_session_feedback_booking_id'))
    )
    op.create_index(op.f('ix_session_feedback_transcript_id'), 'session_feedback', ['transcript_id'], unique=False)
    op.create_table('transcript_speakers',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolved_via', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['session_transcripts.id'], name=op.f('fk_transcript_speakers_transcript_id_session_transcripts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transcript_speakers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_speakers')),
    sa.UniqueConstraint('transcript_id', 'speaker_label', name='uq_transcript_speaker_label')
    )
    op.create_index(op.f('ix_transcript_speakers_transcript_id'), 'transcript_speakers', ['transcript_id'], unique=False)
    # ### end Alembic commands ###

    # Partial indexes on bookings - like the exclusion constraints below,
    # these live here because the models cannot express their WHERE clauses.
    # The unique pair is the "one active booking per learner per session"
    # invariant; the holds index feeds the worker's expiry sweep.
    op.execute(
        "CREATE UNIQUE INDEX uq_bookings_session_learner_active ON bookings (session_id, learner_id) "
        "WHERE (status <> 'cancelled')"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_bookings_one_on_one_learner_active ON bookings (one_on_one_id, learner_id) "
        "WHERE (status <> 'cancelled')"
    )
    op.execute(
        "CREATE INDEX ix_bookings_expiring_holds ON bookings (hold_expires_at) "
        "WHERE (status = 'pending')"
    )

    # Overlap guards. Exclusion constraints are added here rather than in the
    # models because autogenerate cannot express or detect them.
    op.execute(
        "ALTER TABLE instructor_blocks ADD CONSTRAINT ex_instructor_blocks_no_overlap "
        "EXCLUDE USING gist (instructor_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&)"
    )
    op.execute(
        "ALTER TABLE instructor_engagements ADD CONSTRAINT ex_instructor_engagements_no_overlap "
        "EXCLUDE USING gist (instructor_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&)"
    )
    op.execute(
        "ALTER TABLE sessions ADD CONSTRAINT ex_sessions_instructor_no_overlap "
        "EXCLUDE USING gist (instructor_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&) "
        "WHERE (status <> 'cancelled')"
    )
    # 1:1s claim the hour before and after too - prep and wind-down time.
    op.execute(
        "ALTER TABLE one_on_one_sessions ADD CONSTRAINT ex_one_on_one_buffer "
        "EXCLUDE USING gist (instructor_id WITH =, shevaani_buffered_range(starts_at, ends_at, 60) WITH &&) "
        "WHERE (status <> 'cancelled')"
    )
    # A learner cannot sit in two rooms at once, whatever kind of rooms.
    op.execute(
        "ALTER TABLE bookings ADD CONSTRAINT ex_bookings_learner_no_overlap "
        "EXCLUDE USING gist (learner_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&) "
        "WHERE (status IN ('pending', 'confirmed', 'attended', 'no_show'))"
    )

    # Sessions and one-on-ones mirror into instructor_engagements so the
    # exclusion constraint above can police both calendars at once.
    op.execute(
        """
        CREATE FUNCTION shevaani_sync_engagement() RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                DELETE FROM instructor_engagements
                WHERE source = TG_ARGV[0] AND source_id = OLD.id;
                RETURN OLD;
            END IF;

            IF NEW.status = 'cancelled' THEN
                DELETE FROM instructor_engagements
                WHERE source = TG_ARGV[0] AND source_id = NEW.id;
                RETURN NEW;
            END IF;

            INSERT INTO instructor_engagements
                (instructor_id, starts_at, ends_at, source, source_id)
            VALUES (NEW.instructor_id, NEW.starts_at, NEW.ends_at, TG_ARGV[0], NEW.id)
            ON CONFLICT (source, source_id) DO UPDATE SET
                instructor_id = EXCLUDED.instructor_id,
                starts_at     = EXCLUDED.starts_at,
                ends_at       = EXCLUDED.ends_at;
            RETURN NEW;
        END;
        $$
        """
    )
    for table, source in (("sessions", "group"), ("one_on_one_sessions", "one_on_one")):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_sync_engagement
            AFTER INSERT OR UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION shevaani_sync_engagement('{source}')
            """
        )


def downgrade() -> None:
    bind = op.get_bind()
    # Triggers and exclusion constraints fall with their tables; only the
    # functions, types and extension need explicit drops - after the tables.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_speakers_transcript_id'), table_name='transcript_speakers')
    op.drop_table('transcript_speakers')
    op.drop_index(op.f('ix_session_feedback_transcript_id'), table_name='session_feedback')
    op.drop_table('session_feedback')
    op.drop_index(op.f('ix_join_access_logs_booking_id'), table_name='join_access_logs')
    op.drop_table('join_access_logs')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_table('session_transcripts')
    op.drop_index(op.f('ix_session_reminders_session_id'), table_name='session_reminders')
    op.drop_table('session_reminders')
    op.drop_index('uq_session_meetings_session', table_name='session_meetings')
    op.drop_index('uq_session_meetings_one_on_one', table_name='session_meetings')
    op.drop_table('session_meetings')
    op.drop_index(op.f('ix_bookings_session_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_one_on_one_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_learner_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_sessions_starts_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_slug'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_instructor_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_one_on_one_sessions_starts_at'), table_name='one_on_one_sessions')
    op.drop_index(op.f('ix_one_on_one_sessions_instructor_id'), table_name='one_on_one_sessions')
    op.drop_table('one_on_one_sessions')
    op.drop_table('meet_aliases')
    op.drop_table('instructor_engagements')
    op.drop_index(op.f('ix_instructor_blocks_instructor_id'), table_name='instructor_blocks')
    op.drop_table('instructor_blocks')
    op.drop_table('google_credentials')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_impromptu_topics_track'), table_name='impromptu_topics')
    op.drop_index(op.f('ix_impromptu_topics_category'), table_name='impromptu_topics')
    op.drop_table('impromptu_topics')
    op.drop_table('credit_packs')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION shevaani_sync_engagement()")
    op.execute("DROP FUNCTION shevaani_buffered_range(timestamptz, timestamptz, integer)")
    for enum in _ENUMS:
        enum.drop(bind, checkfirst=True)
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
